### PR TITLE
Change import syntax

### PR DESCRIPTION
**Pull request by asimonia**
## Description
Fixed the import syntax to avoid polluting the namespace for models and serializers

## Related Issue
See bangazon_api models.py and serializers.py

## Motivation and Context
Fixed the import syntax to avoid polluting the namespace for models and serializers

## How Has This Been Tested?
Environment runs with zero issues

## Types of changes
 What types of changes does your code introduce? Put an \`x\` in all the boxes that apply: 
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
 Go over all the following points, and put an \`x\` in all the boxes that apply. 
 If you're unsure about any of these, don't hesitate to ask. We're here to help! 
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by mccordgh — APPROVED** [review]
👍

**Review by nchemsak — APPROVED** [review]
👍

**Review by rtwhitfield84 — CHANGES_REQUESTED** [review]
lets figure out this pycache before merging

**Review by rtwhitfield84 — APPROVED** [review]
👍

**Pull request merged**
