### PR TITLE
As create djangoproject

### PR DESCRIPTION
**Pull request by asimonia**
Provide a general summary of your changes in the Title above

## Description
Created:

- updated README.md for virtualenv
- requirements.txt
- django project
- django app for bangazon-api
- super user for admin panel
- migrated sql tables

## Related Issue
**Create Django project** #9

## Motivation and Context
Get the project and app up and running. 

## How Has This Been Tested?
Server runs and is OK.

## Types of changes
 What types of changes does your code introduce? Put an \`x\` in all the boxes that apply: 
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
 Go over all the following points, and put an \`x\` in all the boxes that apply. 
 If you're unsure about any of these, don't hesitate to ask. We're here to help! 
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by danirenae** [comment]
This looks good to me.

**Review by rtwhitfield84 — APPROVED** [review]
i approve 👍

**Review by rtwhitfield84 — APPROVED** [review]
approved 👍

**Review by mccordgh — APPROVED** [review]
A nice starter skeleton! 💀 ☠️

**Comment by nchemsak** [comment]
👍

**Pull request merged**
